### ISSUE TITLE
Umbrella issue for 1.0

### ISSUE THREAD

**Issue by sethp** [sethp/ssh2-config#1]
Dumping my local to-do list before I break these out into individual issues.

- [ ] Single-option parsing correctness
    - [x] Multiple consecutive delimiters
    - [x] ~Quotes in the middle of a token (aka `foo" bar"` -> `foobar`)~ #9
    - [ ] Measuring / reducing the number of allocations when parsing a line?
- [x] ~Some sort of CI~ split out into https://github.com/sethp/ssh2-config/issues/3
- [x] ~Table testing / macros~ #10
    - [x] ~Integration test cleanup~ #5 
    - [x] ~Build completeness test: check options are consumed or explicitly ignored~ #6
- [ ] Host patterns and matching – started under #19 , it turns out the host pattern/matching wasn't the hardest part
- [ ] Apply options to libssh
    - [ ] Is it possible to produce bindings-like autogen from libssh options ?
- [ ] Add some more options
- [x] ~Fuzzing~ #7
- [x] ~Line numbers and file locations for errors~ #14
- [x] ~Documentation~ part of #13 
- [x] ~[About - Rust API Guidelines](https://rust-lang.github.io/api-guidelines/about.html)~ #8
- [ ] Entry point ideas
    - [ ] From subprocess (`ssh -G`)
      - [ ] But: slightly different format (normalized, but no quotes)
    - [ ] From explicit file(s)
    - [ ] From default file load paths
    - [ ] From raw config string
    - [ ] And maybe just the defaults baked into the openssh binary w/o file ops?
